### PR TITLE
feat: add cookie consent and docs feedback

### PR DESCRIPTION
**Pull request by 5A11**
This PR adds cookie consent widget and feedback widget (i.e. `Was this page helpful?` at the bottom every page).
These are based on the upstream features in Material for MkDocs.

### CODE REVIEW

**Review by VijaySharma815 — APPROVED** [review]

**Comment by VijaySharma815** [comment]
@5A11 , I am not seeing any feedback widget at the bottom and when I click on [Change cookie settings](https://fetch-docs-preview--pr277-update-material-new-kb8o7nom.web.app/bug_bounty/#__consent) nothing happen.

**Comment by 5A11** [comment]
> @5A11 , I am not seeing any feedback widget at the bottom and when I click on [Change cookie settings](https://fetch-docs-preview--pr277-update-material-new-kb8o7nom.web.app/bug_bounty/#__consent) nothing happen.

@VijaySharma815 This may be because of specific ways the temp visual is built in CI. Try viewing the docs locally.

**Comment by VijaySharma815** [comment]
@5A11 , I check the docs locally. I am able to see the cookie's consent but still, the feedback widget is not showing. 

**cookies consent:**

cookies consent

**No feedback widget:**

feedback form

**Comment by 5A11** [comment]
> **No feedback widget:**

You need to accept the cookies and refresh the page. 
When you switch to another page unfortunately it doesn’t immediately show the widget. Gotta refresh (edited) 
I think it is a bug in the upstream package

**Pull request merged**
