### PR TITLE
Add cosmpy submodule

### PR DESCRIPTION
**Pull request by 5A11**
Add CosmPy submodule to this repo.

### CODE REVIEW

**Comment by 5A11** [comment]
docs content for `CosmPy` is in the `develop` branch. Must wait for it to go to main before landing this PR (hence the CI failure).

**Comment by daeMOn63** [comment]
@5A11 You can make the cosmpy submodule point to develop commit, that won't cause any troubles. From memory something like:

```
cd cosmpy
git fetch
git checkout develop
git pull origin develop
cd ../
git add cosmpy
git commit...
git push...
```

**Comment by 5A11** [comment]
> @5A11 You can make the cosmpy submodule point to develop commit, that won't cause any troubles. From memory something like:
> 
> ```
> cd cosmpy
> git fetch
> git checkout develop
> git pull origin develop
> cd ../
> git add cosmpy
> git commit...
> git push...
> ```

But then that would always point to the `develop` branch right? If so, that's not what we want. We want it to always point to the `master` versions of all the submodules. 

What we should do is create a `staging` docs that point to the `develop` branch of all the respective submodules just to be able to see everything that's coming up in the next releases. I believe Ian's ECO-1194 Jira task is on this.

**Comment by daeMOn63** [comment]
> But then that would always point to the `develop` branch right? If so, that's not what we want. We want it to always point to the `master` versions of all the submodules.
> 
> What we should do is create a `staging` docs that point to the `develop` branch of all the respective submodules just to be able to see everything that's coming up in the next releases. I believe Ian's ECO-1194 Jira task is on this.

Nope, submodules tracks a single commit under the hood. Branch are just labels applied on specific a commit. So in any case, new commits on master or develop of fetchd won't show up here, until someone manually updates the submodule reference to point to another commit.

**Review by ejfitzgerald — APPROVED** [review]

**Pull request merged**
